# Generated by Django 2.1.4 on 2018-12-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=64, unique=True)),
                ('hostname', models.CharField(default='', max_length=128)),
                ('ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('mac', models.CharField(max_length=32)),
                ('platform', models.CharField(default='CentOS', max_length=128)),
                ('arch', models.CharField(default='', max_length=16)),
                ('cpu', models.IntegerField(default=0)),
                ('mem', models.BigIntegerField(default=0)),
                ('pid', models.IntegerField(default=0)),
                ('time', models.FloatField(default=0)),
                ('user', models.CharField(default='', max_length=64)),
                ('application', models.CharField(default='', max_length=64)),
                ('addr', models.CharField(default='', max_length=256)),
                ('remark', models.CharField(default='', max_length=256)),
                ('heartbeat_time', models.DateTimeField(auto_now_add=True)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
