# Generated by Django 2.1.4 on 2018-12-23 18:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='', max_length=64, unique=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('cpu', models.FloatField(default=0)),
                ('mem', models.FloatField(default=0)),
            ],
            bases=(api.models.Attr2DictMixin, models.Model),
        ),
    ]
